name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ~/.android/sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Install Android SDK 36
        run: |
          yes | sdkmanager "platforms;android-36" "build-tools;34.0.0"
            
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
